@startuml
title: Singleton

class PaymentRepository {
    private static PaymentRepository paymentRepository = new PaymentRepository();
    private PaymentRepository();
    public getInistance();
}
@enduml
